import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: ["tests/unit/**/*.test.ts"],
    reporters: ["default"],
    coverage: {
      provider: "v8",
      include: [
        "lib/game/core/random.ts",
        "lib/game/core/SystemPipeline.ts",
        "lib/game/core/FeatureRegistry.ts",
        "lib/game/world/terrain.ts",
        "lib/game/world/geometry.ts",
        "lib/game/world/macroWorld.ts",
        "lib/game/world/roads.ts",
        "lib/game/world/vegetation.ts",
        "lib/game/world/surfaceVariation.ts",
        "lib/game/world/WaterSurface.ts",
        "lib/game/animals/animalRecipes.ts",
        "lib/game/animals/AnimalEngine.ts",
        "lib/game/equipment/PlayerFlashlight.ts",
        "lib/game/audio/model.ts",
        "lib/game/settings.ts",
        "lib/game/persistence/PreferencesStore.ts",
        "lib/game/systems/PlayerEquipmentSystem.ts",
        "lib/game/systems/PlayerConditionSystem.ts",
        "lib/game/systems/LocationDiscoverySystem.ts",
        "lib/game/systems/EnvironmentalAudioSystem.ts",
        "lib/game/systems/ScannerSystem.ts",
        "lib/game/world/spawnBuilding.ts",
        "lib/game/world/authoredDoor.ts",
        "lib/game/world/twoStoryBuilding.ts",
        "lib/game/world/tenStoryBuilding.ts",
        "lib/game/citizens/citizenRecipes.ts",
        "lib/game/gameplay/items.ts",
        "lib/game/gameplay/contracts.ts",
        "lib/game/gameplay/crafting.ts",
        "lib/game/gameplay/fieldGuide.ts",
        "lib/game/gameplay/interactions.ts",
        "lib/game/gameplay/interactionPrompt.ts",
        "lib/game/gameplay/loot.ts",
        "lib/game/gameplay/playerCondition.ts",
        "lib/game/gameplay/progression.ts",
        "lib/game/gameplay/resting.ts",
        "lib/game/navigation/math.ts",
        "lib/game/navigation/NavigationService.ts",
        "lib/game/navigation/presentation.ts",
        "lib/game/environment/model.ts",
        "lib/game/developer/environmentState.ts",
        "lib/game/world/fastTravel.ts",
        "lib/game/world/locationDiscovery.ts",
        "lib/game/world/inspectables.ts",
        "lib/game/systems/EnvironmentSystem.ts",
        "lib/game/systems/collision.ts",
        "lib/game/systems/locomotion.ts",
        "lib/game/state.ts",
        "lib/game/persistence/SaveStore.ts",
      ],
      reporter: ["text", "html", "json-summary"],
      thresholds: {
        lines: 88,
        functions: 88,
        branches: 82,
        statements: 88,
      },
    },
  },
});
