import { defineConfig } from "vitest/config";

/**
 * Source files under the unit-coverage gate. Browser-owned renderer and PMREM
 * lifecycles need a real WebGL2 context and are tested in Playwright instead:
 * Engine.ts, RenderPipeline.ts and EnvironmentMapRuntime.ts stay out, as do
 * the thin system installers only Engine exercises and type-only modules
 * (coverage reports a file with no statements as 0%).
 */
const COVERED_FILES = [
  "lib/game/world/ChunkManager.ts",
  "lib/game/environment.ts",
  "lib/game/world/canyonLandmark.ts",
  "lib/game/world/mountainLandmark.ts",
  "lib/game/animals/groundMotion.ts",
  "lib/game/config.ts",
  "lib/game/core/events.ts",
  "lib/game/core/random.ts",
  "lib/game/core/SystemPipeline.ts",
  "lib/game/core/FeatureRegistry.ts",
  "lib/game/world/terrain.ts",
  "lib/game/world/heightBounds.ts",
  "lib/game/world/geometry.ts",
  "lib/game/world/macroWorld.ts",
  "lib/game/world/roads.ts",
  "lib/game/world/vegetation.ts",
  "lib/game/world/surfaceVariation.ts",
  "lib/game/world/WorldLodPolicy.ts",
  "lib/game/world/sceneryLod.ts",
  "lib/game/world/benchmarkZone.ts",
  "lib/game/world/WaterSurface.ts",
  "lib/game/world/authoredBuildings.ts",
  "lib/game/world/buildingTypes.ts",
  "lib/game/world/spawnFeatures.ts",
  "lib/game/world/deployments.ts",
  "lib/game/animals/animalRecipes.ts",
  "lib/game/animals/AnimalEngine.ts",
  "lib/game/equipment/PlayerFlashlight.ts",
  "lib/game/audio/model.ts",
  "lib/game/audio/EnvironmentalAudio.ts",
  "lib/game/npcs/model.ts",
  "lib/game/npcs/stillpointNpcs.ts",
  "lib/game/npcs/presentation.ts",
  "lib/game/npcs/authoredNpc.ts",
  "lib/game/rendering/Bloom.ts",
  "lib/game/rendering/PostProcessShader.ts",
  "lib/game/rendering/RenderingPolicy.ts",
  "lib/game/rendering/GraphicsCapabilities.ts",
  "lib/game/rendering/ShortRangeGtaoPass.ts",
  "lib/game/rendering/WorldMaterialLibrary.ts",
  "lib/game/rendering/GpuFrameTimer.ts",
  "lib/game/developer/GraphicsBenchmark.ts",
  "lib/game/developer/PlayerSandbox.ts",
  "lib/game/camera/CameraRig.ts",
  "lib/game/camera/PlayerAvatar.ts",
  "lib/game/settings.ts",
  "lib/game/input/InputManager.ts",
  "lib/game/ui/dialogFocus.ts",
  "lib/game/persistence/PreferencesStore.ts",
  "lib/game/systems/PlayerEquipmentSystem.ts",
  "lib/game/systems/CameraControlSystem.ts",
  "lib/game/systems/PlayerConditionSystem.ts",
  "lib/game/systems/PlayerControllerSystem.ts",
  "lib/game/systems/LocationDiscoverySystem.ts",
  "lib/game/systems/EnvironmentalAudioSystem.ts",
  "lib/game/systems/ScannerSystem.ts",
  "lib/game/systems/InteractionSystem.ts",
  "lib/game/world/spawnBuilding.ts",
  "lib/game/world/authoredDoor.ts",
  "lib/game/world/twoStoryBuilding.ts",
  "lib/game/world/tenStoryBuilding.ts",
  "lib/game/citizens/citizenRecipes.ts",
  "lib/game/gameplay/items.ts",
  "lib/game/gameplay/contracts.ts",
  "lib/game/gameplay/deploymentPlacement.ts",
  "lib/game/gameplay/contractEvidence.ts",
  "lib/game/gameplay/crafting.ts",
  "lib/game/gameplay/fieldGuide.ts",
  "lib/game/gameplay/interactions.ts",
  "lib/game/gameplay/interactionPrompt.ts",
  "lib/game/gameplay/loot.ts",
  "lib/game/gameplay/playerCondition.ts",
  "lib/game/gameplay/progression.ts",
  "lib/game/gameplay/resting.ts",
  "lib/game/navigation/math.ts",
  "lib/game/navigation/NavigationService.ts",
  "lib/game/navigation/presentation.ts",
  "lib/game/cartography/viewport.ts",
  "lib/game/session/sessionPresets.ts",
  "lib/game/environment/model.ts",
  "lib/game/developer/environmentState.ts",
  "lib/game/world/fastTravel.ts",
  "lib/game/world/locationDiscovery.ts",
  "lib/game/world/inspectables.ts",
  "lib/game/systems/EnvironmentSystem.ts",
  "lib/game/systems/collision.ts",
  "lib/game/systems/locomotion.ts",
  "lib/game/state.ts",
  "lib/game/persistence/SaveStore.ts",
  "lib/game/world/HorizonRenderer.ts",
  "lib/game/world/ChunkAssetCache.ts",
  "lib/game/world/RoadSurfaceGeometry.ts",
  "lib/game/world/authoredLandmarks.ts",
  "lib/game/world/worldWater.ts",
  "lib/game/rendering/AdaptiveResolution.ts",
  "lib/game/rendering/BlobShadows.ts",
  "lib/game/rendering/CelestialDiscs.ts",
  "lib/game/rendering/GraphicsFeatures.ts",
  "lib/game/rendering/ProceduralSurfaceDetail.ts",
  "lib/game/rendering/ShadowBias.ts",
  "lib/game/rendering/ShadowUpdatePolicy.ts",
  "lib/game/rendering/SharedWorldUniforms.ts",
  "lib/game/rendering/VegetationWind.ts",
  "lib/game/citizens/CitizenEngine.ts",
  "lib/game/animals/reactions.ts",
  "lib/game/developer/ForestStressTest.ts",
];

/**
 * Each covered file must also clear this floor on its own, so the aggregate
 * cannot hide one file losing its tests. It sits at the weakest covered file;
 * raise it as those files gain tests.
 */
const PER_FILE_FLOOR = { statements: 65, branches: 50, functions: 50, lines: 65 };

export default defineConfig({
  test: {
    environment: "node",
    include: ["tests/unit/**/*.test.ts"],
    reporters: ["default"],
    // Chunk construction is CPU-heavy. Bound contention without relaxing tests.
    maxWorkers: 2,
    coverage: {
      provider: "v8",
      include: COVERED_FILES,
      reporter: ["text", "html", "json-summary"],
      thresholds: {
        lines: 88,
        functions: 88,
        branches: 82,
        statements: 88,
        // Vitest checks the files matching each glob as one group, so an
        // exact-path glob is a per-file floor. Every file still counts in the
        // aggregate above.
        ...Object.fromEntries(COVERED_FILES.map((file) => [file, PER_FILE_FLOOR])),
      },
    },
  },
});
